# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: netbox-db
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Chart.Name }}-postgresql

---

apiVersion: v1
kind: Service
metadata:
  name: netbox-redis
spec:
  ports:
    - port: 6379
  selector:
    app: {{ .Chart.Name }}-redis

---

apiVersion: v1
kind: Service
metadata:
  name: netbox
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 13031
  selector:
    app: {{ .Chart.Name }}-netbox
