# values.yaml
postgresql:
  image: postgres:15-alpine
  volumes:
    - name: netbox_pg_data
      mountPath: /var/lib/postgresql/data
  env:
    POSTGRES_PASSWORD: ""
    POSTGRES_DB: netbox
    POSTGRES_USER: netbox

redis:
  image: redis:7-alpine
  user: "1000:1000"
  command: redis-server
  volumes:
    - name: netbox_redis_data
      mountPath: /data

netbox:
  image: lscr.io/linuxserver/netbox:latest
  containerName: netbox
  env:
    PUID: 1000
    PGID: 1000
    TZ: Europe/Amsterdam
    SUPERUSER_EMAIL: ""
    SUPERUSER_PASSWORD: ""
    ALLOWED_HOST: ""
    DB_NAME: netbox
    DB_USER: netbox
    DB_PASSWORD: ""
    DB_HOST: netbox-db
    DB_PORT: 5432
    REDIS_HOST: netbox-redis
    REDIS_PORT: 6379
    REDIS_DB_TASK: 0
    REDIS_DB_CACHE: 1
  volumes:
    - name: netbox_config
      mountPath: /config
  ports:
    - 13031:8000
  dependsOn:
    - netbox-db
    - netbox-redis
